version: '3.3'
services:
  web:
    build:
      context: ./image
      dockerfile: Dockerfile
    container_name: wildfly_MultaApp
    environment:
      - WILDFLY_USER=JCG
      - WILDFLY_PASS=proyectofinal
      - DB_NAME=vehiculoMulta
      - DB_USER=JCG
      - DB_PASS=proyectofinal
      - DB_URI=db:3306
    depends_on:
      - db
    ports:
      - 8080:8080
      - 9990:9990
      - 8009:8009
    volumes:
      - type: bind
        source: ./deployment
        target: /opt/jboss/wildfly/standalone/deployments
  db:
    container_name: myDataBase_MultaApp
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehiculoMulta
      MYSQL_USER: JCG
      MYSQL_PASSWORD: proyectofinal
    ports:
      - 7144:3306
    cap_add:
      - SYS_NICE
    security_opt:
    - seccomp:unconfined
  admin_db:
    container_name: Admin_db_MultaApp
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 3000:80
networks:
    default:
        driver: bridge
