-- MySQL Script generated by MySQL Workbench
-- mié 23 sep 2020 18:52:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `mydb`.`persona_tabla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persona_tabla` (
  `documento` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiculo_tabla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehiculo_tabla` (
  `placa` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NOT NULL,
  `anio` DATE NOT NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conductor_tabla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conductor_tabla` (
  `persona_tabla_documento` INT NOT NULL,
  `fecha_expedicion_licencia` DATE NOT NULL,
  `fecha_expiracion_licencia` DATE NOT NULL,
  `vehiculo_tabla_placa` VARCHAR(255) NOT NULL,
  `vehiculo_tabla_placa1` VARCHAR(255) NOT NULL,
  INDEX `fk_conductor_tabla_persona_tabla_idx` (`persona_tabla_documento` ASC) VISIBLE,
  INDEX `fk_conductor_tabla_vehiculo_tabla1_idx` (`vehiculo_tabla_placa1` ASC) VISIBLE,
  PRIMARY KEY (`persona_tabla_documento`),
  CONSTRAINT `fk_conductor_tabla_persona_tabla`
    FOREIGN KEY (`persona_tabla_documento`)
    REFERENCES `persona_tabla` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conductor_tabla_vehiculo_tabla1`
    FOREIGN KEY (`vehiculo_tabla_placa1`)
    REFERENCES `vehiculo_tabla` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agente_tabla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agente_tabla` (
  `numero_agente` INT NOT NULL,
  INDEX `fk_agente_tabla_persona_tabla1_idx` (`numero_agente` ASC) VISIBLE,
  PRIMARY KEY (`numero_agente`),
  CONSTRAINT `fk_agente_tabla_persona_tabla1`
    FOREIGN KEY (`numero_agente`)
    REFERENCES `persona_tabla` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`multa_tabla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multa_tabla` (
  `id_multa_tabla` INT NOT NULL,
  `conductor_documento` INT NOT NULL,
  `agente_agente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado_multa` VARCHAR(45) NOT NULL,
  `valor_multa` INT NOT NULL,
  PRIMARY KEY (`id_multa_tabla`),
  INDEX `fk_multa_tabla_conductor_tabla1_idx` (`conductor_documento` ASC) VISIBLE,
  INDEX `fk_multa_tabla_agente_tabla1_idx` (`agente_agente` ASC) VISIBLE,
  CONSTRAINT `fk_multa_tabla_conductor_tabla1`
    FOREIGN KEY (`conductor_documento`)
    REFERENCES `conductor_tabla` (`persona_tabla_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_multa_tabla_agente_tabla1`
    FOREIGN KEY (`agente_agente`)
    REFERENCES `agente_tabla` (`numero_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
